services:
  vintage-story:
    image: vintage-story:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vs-server
    restart: unless-stopped
    ports:
      - "42420:42420"
    volumes:
      - ./data:/var/vintagestory/data
    environment:
      - TZ=Europe/London # Set to your timezone
      - VERSION=1.20.7 # Game version - works with release candidates (unstable) as well as regular releases (stable)
    stdin_open: true
    tty: true
    user: "1000:1000"
